//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DekkSkate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skateboards
    {
        public int SkateboardID { get; set; }
        public string Brand { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string url { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Email { get; set; }
        public Nullable<int> stock { get; set; }
        public string Model { get; set; }
        public string address { get; set; }
        public string advice { get; set; }
    }
}
